version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc.123456
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app_network

  api:
    build: .
    container_name: api_biblioteca
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=API_Biblioteca_01_DB;User Id=sa;Password=Abc.123456;TrustServerCertificate=True;
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sql_data:
